### ISSUE TITLE
Support nested font syntax

### ISSUE THREAD

**Issue by nvkelso** [tangrams/bundler#4]
Looks like newer Tangram syntax allows another level of nesting for fonts. The fonts should be present in the ZIP using the newer syntax.

But when I run a newer style like Bubble Wrap the fonts are missing in the ZIP (but Tron still works) :\

**Tron** 

```
fonts:
    Aldrich:
        # url: https://fonts.gstatic.com/s/aldrich/v6/VWXaIPGrUapL_Y2vGs0lKALUuEpTyoUstqEm5AMlJo4.woff
        url: fonts/VWXaIPGrUapL_Y2vGs0lKALUuEpTyoUstqEm5AMlJo4.woff
```

**Bubble Wrap**

```
fonts:
    Open Sans:
        - weight: 300 # Light
          url: fonts/OpenSans-Light.woff
        - weight: normal # Regular
          url: fonts/OpenSans-Regular.woff
        - weight: normal # Regular
          style: italic
          url: fonts/OpenSans-Italic.woff
```
